# Generated by Django 4.0.2 on 2022-03-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_customer_books_b_id_books_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='bname',
        ),
    ]
