# Generated by Django 4.0.2 on 2022-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_rename_name_books_bname'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='phnob',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='b_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
