# Generated by Django 4.0.2 on 2022-03-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_books_phnob_alter_books_b_id_alter_customer_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cityb',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='colb',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='soldb',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
